# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gRPC_service.proto import checkPrime_pb2 as proto_dot_checkPrime__pb2


#used for client
class CheckPrimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidatePrime = channel.unary_unary(
                '/CheckPrimeService/ValidatePrime',
                request_serializer=proto_dot_checkPrime__pb2.inputRequest.SerializeToString,
                response_deserializer=proto_dot_checkPrime__pb2.outputResponse.FromString,
                )

#used for server
class CheckPrimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""
    pass
    def ValidatePrime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckPrimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidatePrime': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePrime,
                    request_deserializer=proto_dot_checkPrime__pb2.inputRequest.FromString,
                    response_serializer=proto_dot_checkPrime__pb2.outputResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CheckPrimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckPrimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidatePrime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CheckPrimeService/ValidatePrime',
            proto_dot_checkPrime__pb2.inputRequest.SerializeToString,
            proto_dot_checkPrime__pb2.outputResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
