# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/checkPrime.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/checkPrime.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16proto/checkPrime.proto\"\x1e\n\x0cinputRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\" \n\x0eoutputResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32\x44\n\x11\x43heckPrimeService\x12/\n\rValidatePrime\x12\r.inputRequest\x1a\x0f.outputResponseb\x06proto3'
)




_INPUTREQUEST = _descriptor.Descriptor(
  name='inputRequest',
  full_name='inputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='inputRequest.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_OUTPUTRESPONSE = _descriptor.Descriptor(
  name='outputResponse',
  full_name='outputResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='outputResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['inputRequest'] = _INPUTREQUEST
DESCRIPTOR.message_types_by_name['outputResponse'] = _OUTPUTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

inputRequest = _reflection.GeneratedProtocolMessageType('inputRequest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTREQUEST,
  '__module__' : 'proto.checkPrime_pb2'
  # @@protoc_insertion_point(class_scope:inputRequest)
  })
_sym_db.RegisterMessage(inputRequest)

outputResponse = _reflection.GeneratedProtocolMessageType('outputResponse', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTRESPONSE,
  '__module__' : 'proto.checkPrime_pb2'
  # @@protoc_insertion_point(class_scope:outputResponse)
  })
_sym_db.RegisterMessage(outputResponse)



_CHECKPRIMESERVICE = _descriptor.ServiceDescriptor(
  name='CheckPrimeService',
  full_name='CheckPrimeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=92,
  serialized_end=160,
  methods=[
  _descriptor.MethodDescriptor(
    name='ValidatePrime',
    full_name='CheckPrimeService.ValidatePrime',
    index=0,
    containing_service=None,
    input_type=_INPUTREQUEST,
    output_type=_OUTPUTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHECKPRIMESERVICE)

DESCRIPTOR.services_by_name['CheckPrimeService'] = _CHECKPRIMESERVICE

# @@protoc_insertion_point(module_scope)
